// <auto-generated />
using System;
using ListedLinks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListedLinks.Migrations
{
    [DbContext(typeof(ListedLinksContext))]
    partial class ListedLinksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ListedLinks.Models.Comment", b =>
                {
                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Text", "CreatedAt");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ListedLinks.Models.IPAddressString", b =>
                {
                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("IPAddress");

                    b.ToTable("IPAddressStrings");
                });

            modelBuilder.Entity("ListedLinks.Models.ListedLink", b =>
                {
                    b.Property<int>("ListedLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("ListedLinkId");

                    b.ToTable("ListedLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
