name:  Test Deployment Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: rsync deployment
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: ListedLinks/
        remote_path: /root/deployments/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: build on remote
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Reference the private key stored in GitHub Secrets
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Establish an SSH connection and execute commands on the remote server
        ssh -o StrictHostKeyChecking=no -i private_key.pem root@159.89.253.102 <<EOF
          systemctl stop kestrel-biffkittz.service

          cp -f /var/www/biffkittz/ListedLinks.db /tmp/ListedLinks.db
          cp -f /var/www/biffkittz/ListedLinks.db /tmp/ListedLinks-bk.db
          rm -rf /var/www/biffkittz
          mkdir /var/www/biffkittz

          dotnet publish /root/deployments/ListedLinks.csproj -r linux-x64 --self-contained

          cp -rf /root/deployments/bin/Release/net8.0/linux-x64/* /var/www/biffkittz/
          cp -f /tmp/ListedLinks.db /var/www/biffkittz/ListedLinks.db

          nginx -t
          nginx -s reload

          systemctl start kestrel-biffkittz.service
        EOF

        rm -f private_key.pem
