name:  Deploy Site
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: rsync copy
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: ListedLinks/
        remote_path: /root/deployments/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  publish:
    needs: sync
    runs-on: ubuntu-latest
    steps:
    - name: build on remote
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Reference the private key stored in GitHub Secrets
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: ${{ secrets.SSH_PORT }}
          APP_SETTINGS: ${{ secrets.APP_SETTINGS }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        echo "$APP_SETTINGS" > appsettings.json
        chmod 600 private_key.pem
        scp -v -i private_key.pem -o StrictHostKeyChecking=no appsettings.json root@159.89.253.102:/root/deployments/

        # Establish an SSH connection and execute commands on the remote server
        ssh -o StrictHostKeyChecking=no -i private_key.pem root@159.89.253.102 <<EOF
          sudo systemctl stop kestrel-biffkittz.service

          sudo cp -f /var/www/biffkittz/ListedLinks.db /tmp/ListedLinks.db
          sudo cp -f /var/www/biffkittz/ListedLinks.db /tmp/ListedLinks-bk.db
          sudo rm -rf /var/www/biffkittz
          sudo mkdir /var/www/biffkittz

          sudo dotnet publish /root/deployments/ListedLinks.csproj -r linux-x64 --self-contained

          sudo cp -rf /root/deployments/bin/Release/net8.0/linux-x64/* /var/www/biffkittz/
          sudo cp -f /tmp/ListedLinks.db /var/www/biffkittz/ListedLinks.db

          sudo nginx -t
          sudo nginx -s reload

          sudo systemctl start kestrel-biffkittz.service
        EOF

        rm -f private_key.pem
