# TODO: Does not work, needs adaptation
# PREREQ Set up SSH access to the server: https://askubuntu.com/questions/1097038/how-do-i-setup-ssh-key-based-authentication-for-github-by-using-ssh-config-fi
#   sudo apt update && sudo apt install -y openssh-client git
#   mkdir -p -m 700 ~/.ssh/github
#   ssh-keygen -t ed25519 -C 'biffkittz@gmail.com' -f ~/.ssh/github/id_ed25519 -q -N ''

name: CI
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to biffkittz"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/biffkittz.key
          chmod 600 ~/.ssh/biffkittz.key
          cat >>~/.ssh/config <<END
          Host biffkittz
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/biffkittz.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      #- name: Stop the server
      #  run: ssh biffkittz 'sudo ls -als /var/www/biffkittz'

      - name: Echo secrets for debug
        run: echo "$SSH_HOST"

      # - name: Start the server
      #   if: ${{ always() }}
      #   run: ssh biffkittz 'sudo systemctl start my-application'
